In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [29]:
def f_example_2(x,y):
    # return x**4+0.8*y**4+4*x**2+2*y**2-x*y-0.2*x**2*y
     return x**4 + 0.8*y**4 + 4*x**2 + 2*y**2 - x*y -0.2*x**2*y
def f_grad_example_2(x,y):
    # return np.array([[4*x**3+8*x**3-y-0.4*x*y],[3.2*y**3+4*y-0.2*x**2]])
    return np.array([[4*x**3 + 8*x - y - 0.4*x*y],
                     [3.2*y**3 +4*y - x - 0.2*x**2]])

def f_hessian_example_2(x,y):
    # return np.array([[12*x**2+24*x-0.4, -1-0.4*x],[-1-0.4*x, 9.6*y**2-4]])
    return np.array([[12*x**2 + 8 - 0.4*y, -1 - 0.4*x],
                         [-1 - 0.4*x, 9.6*y**2 + 4]])

def gradient_decent_2(grad,x_y,learning_rate=0.01,num_iterations=25):
    for iteration in range(num_iterations):
        x_y=x_y-learning_rate*grad(x_y[0,0],x_y[1,0])
        print(x_y.T)
    return x_y

def newton_method_2(grad,hessian,x_y,num_iterations=25):
    for iteration in range(num_iterations):
        x_y=x_y-np.matmul(np.linalg.inv(hessian(x_y[0,0],x_y[1,0])),grad(x_y[0,0],x_y[1,0]))
        print(x_y.T)
    return x_y    

In [33]:
x_y=np.array([[4],[4]])



In [35]:
print(f_example_2(x_y[0,0],x_y[1,0]))
print(f_grad_example_2(x_y[0,0],x_y[1,0]))
print(f_hessian_example_2(x_y[0,0],x_y[1,0]))

528.0
[[277.6]
 [213.6]]
[[198.4  -2.6]
 [ -2.6 157.6]]


In [36]:
gradient_decent_2(f_grad_example_2,x_y)


[[1.224 1.864]]
[[1.08049545 1.59742961]]
[[0.96647631 1.41623101]]
[[0.87268502 1.28021711]]
[[0.79355655 1.17211542]]
[[0.72552462 1.08289572]]
[[0.66617804 1.00725201]]
[[0.61381454 0.94181004]]
[[0.56718923 0.8842968 ]]
[[0.52536464 0.83311212]]
[[0.48761715 0.78708953]]
[[0.45337623 0.74535415]]
[[0.42218371 0.70723417]]
[[0.3936657  0.67220329]]
[[0.36751268 0.63984208]]
[[0.34346515 0.60981126]]
[[0.32130313 0.58183274]]
[[0.30083818 0.55567598]]
[[0.28190749 0.53114779]]
[[0.26436916 0.50808482]]
[[0.24809868 0.48634771]]
[[0.23298606 0.46581668]]
[[0.21893358 0.44638803]]
[[0.20585393 0.42797136]]
[[0.1936688  0.41048741]]


array([[0.1936688 ],
       [0.41048741]])

In [37]:
newton_method_2(f_grad_example_2,f_hessian_example_2,x_y)

[[2.58273866 2.62128884]]
[[1.59225691 1.67481611]]
[[0.87058917 1.00182107]]
[[0.33519431 0.49397623]]
[[0.04123585 0.12545903]]
[[0.00019466 0.00301029]]
[[-2.48536390e-08  3.55365461e-08]]
[[ 4.15999751e-17 -2.04850948e-17]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]


array([[0.],
       [0.]])