In [3]:
# importing some packages
import numpy as np

# Get an int helper function            
def get_integer(prompt):
    while True:
        user_input = input(prompt)
        try:
            n= int(user_input)   
            return n
        except ValueError:
            print("Invalid input. Please try again.")

# Using square matrixs for pratise

# Getting the n_th from the user
n_th=get_integer("Enter an integer: ");


# Setting the size of both the coeficients matrix (Martix A) and the constants matrix (Martix B)
A=np.zeros(n_th*n_th,dtype=np.dtype(float))
B=np.zeros(n_th,dtype=np.dtype(float))

# Prompting the user enter the elements of the Matrix A
print(f"Enter the {n_th*n_th} elements of the matrix A")

# Looping to get all the elements and store them in the Matrix A
for i in range(n_th*n_th):
    A[i]=get_integer(f"Enter {i}th element: ")
    # A[i]=input();
    
# Prompting the user enter the elements of the Matrix B
print(f"Enter the {n_th} elements of the matrix B")

# Looping to get all the elements and store them in the Matrix A
for i in range(n_th):
    B[i]=get_integer(f"Enter {i}th element: ")
    # B[i]=input(f"Enter {i}th element: ");  
# Reshaping Matrix A before the upcoming operation
A=np.reshape(A,(n_th,n_th))
        
# Check the singularity of Matrix A
A_det=np.linalg.det(A)

print(A)
print(B)

if A_det !=0:
    print(f"Determinant of matrix is {A_det:.0f}, thus the system has a unique solution")
    # if there is a solution then here is the result
    S=np.linalg.solve(A,B) 
    print(f"The solution of matrixs A and B is:",S)
else:
    print(f"Determinant of matrix is {A_det:.0f}, thus the system has either no solution or many solution")



Enter an integer:  3


Enter the 9 elements of the matrix A


Enter 0th element:  1
Enter 1th element:  2
Enter 2th element:  f


Invalid input. Please try again.


Enter 2th element:  3
Enter 3th element:  4
Enter 4th element:  g


Invalid input. Please try again.


Enter 4th element:  5
Enter 5th element:  6
Enter 6th element:  7
Enter 7th element:  8
Enter 8th element:  9


Enter the 3 elements of the matrix B


Enter 0th element:  2
Enter 1th element:  3
Enter 2th element:  2


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[2. 3. 2.]
Determinant of matrix is 0, thus the system has a unique solution
The solution of matrixs A and B is: [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
